### ISSUE TITLE
Show asyn initialisations in section 3: Synchronisation

### ISSUE THREAD

**Issue by stroobandt** [peterhinch/micropython-async#10]
The import of the separate `async` module as well as `Event`, `Barrier` and `Semaphore` initialisations are not explicitly shown in the examples of section 3.
It is mentioned in the introduction to section 3, but this may easily be overlooked when one jumps from one subsection to the other using the bookmarks in the table of contents.

At least, that is what happened to me yesterday and it took me a bit before it dawned on me that I needed to import an additional module.

An explicit link to the `async` GitHub repository would equally be a handy addition.

Cheers!

**Comment by peterhinch** [comment]
Thanks for the comments. I have updated the tutorial and would be glad for any further feedback.
