### ISSUE TITLE
`uasyncio` is now renamed to `asyncio` in latest

### ISSUE THREAD

**Issue by dburles** [peterhinch/micropython-async#110]
Just a heads up. `uasyncio` is now renamed to `asyncio` in latest version of MicroPython (see [PR](https://github.com/micropython/micropython/pull/11740)). [Found a broken link here](https://github.com/peterhinch/micropython-async/blob/master/v3/README.md?plain=1#L9). There may be other areas that need updating.

**Comment by peterhinch** [comment]
Thank you. I'm aware of the renaming - I intend to update the docs after the next MP release (1.21). I've fixed the broken link.

**Comment by dburles** [comment]
No problem. Figured that it might be worth resolving the broken link in the meantime. Thanks.
