### ISSUE TITLE
Where is ESwitch?

### ISSUE THREAD

**Issue by beetlegigg** [peterhinch/micropython-async#113]
Hello Peter, I have just used your Switch class as found in V3 > primitives > switch. (very nice too and I have it working with events).  But then I read your docs on event programming and it says use  .from primitives import ESwitch'  but I cannot find the ESwitch in the primitives anywhere.   So I'm confused.  Where do I find the ESwitch?   (I probably just need a stronger cup of coffee :-) )

**Comment by peterhinch** [comment]
If you look at the "lazy loader" in [__init__.py](https://github.com/peterhinch/micropython-async/blob/master/v3/primitives/__init__.py) you'll see that it's in `events.py`. Docs are [here](https://github.com/peterhinch/micropython-async/blob/master/v3/docs/EVENTS.md#61-eswitch).
