### ISSUE TITLE
Detected simultaneous button presses with SwArray

### ISSUE THREAD

**Issue by saraverbeecke** [peterhinch/micropython-async#121]
Hi @peterhinch,
I used your normal async button handling, but I'm switching my design to use a button array since I now use a 16 button keypad. The SwArray class looks very promising for this task but is it possible to detect an event where the user presses 2 buttons at the same time?
Thanks!

**Comment by peterhinch** [comment]
See [this paragraph](https://github.com/peterhinch/micropython-async/blob/master/v3/docs/DRIVERS.md#12-switches).

**Comment by saraverbeecke** [comment]
OK, thank you Peter.
