### ISSUE TITLE
Memory Allocation Failed

### ISSUE THREAD

**Issue by Ekiszzero** [peterhinch/micropython-async#13]
I'm beginner and my limited knowledge of english doesn't help me. However, I've been trying to decoder the remote control of my devices using your code.

I'm using a NODEMCU and a YS-IRYM (v2.2) sensor but the issue is this: After uploaded the files to the root of the microcontroller (files together in the root: aremote.py, art.py, asyn.py) when I try to run art.py (uploaded to the root as main.py) it is displayed this error: 

File "main.py", line 18, in <module>
File "aremote.py", line 9, in <module>
MemoryError: memory allocation failed, allocating %u bytes

I'd would really appreciate that you give me a hand, 

Thanks,

**Comment by peterhinch** [comment]
These questions are best raised in [the forum](https://forum.micropython.org/) where they will be viewed and potentially solved by many more people. Gihub is for bug reports.

ESP8266 platforms have limited RAM so you need to implement large libraries as frozen bytecode. I would do this for the above modules and the **uasyncio** library. You'll need to learn how to build the firmware from source and deploy it to the target board. Once you've grasped this, then freezing the modules is a matter of placing them in the  ports/esp8266/modules directory and re-compiling.
