### ISSUE TITLE
FAQ ?

### ISSUE THREAD

**Issue by diginfo** [peterhinch/micropython-async#23]
Hi;

Posted on the micropython forum but no replies, so am adding here.

Is it possible to create a stand-alone asyncio class that can be called from code that does not import uasyncio and does not use uasyncio libs ?

**Comment by peterhinch** [comment]
I'm puzzled why you'd want to - some component of the application must import **uasyncio** so you won't save RAM. But I can't see any reason why you couldn't write
```python
import something

class Foo:
    async def bar(self):
        while True:
            # do something
            yield 100  # == await uasyncio.sleep_ms(100)

    async def rats(self):
        e = something.Else()  # Awaitable class instance
        while True:
            await e
```
Note that `yield 100` is an undocumented feature of **uasyncio**: it's not portable to CPython and it might not be supported in the future.
