### ISSUE TITLE
StreamReader sreader.read() not works on asyncio v3.

### ISSUE THREAD

**Issue by beyonlo** [peterhinch/micropython-async#44]
Hi Piter.

I have this code already perfect working in my application running on MicroPython 1.11.0, using asyncio v2 of course:

```
async def uart_receive():
    sreader = asyncio.StreamReader(uart)
    while True:
        await asyncio.sleep(1)
        res = await sreader.read()
        print('Received from UART: {}'.format(res))

```

Now I trying to port it to v3 (using MicroPython 1.12) , but this code not works anymore on uasyncio v3. I have this error:

```
Task exception wasn't retrieved
future: <Task> coro= <generator object 'uart_receive' at 3f8200e0>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "umain.py", line 177, in uart_receive
TypeError: function takes 2 positional arguments but 1 were given

```

Ps: if I change from `sreader.read()` to `sreader.readline()` works on uasyncio v3, but I want to continue to use `sreader.read()`.

Thank you so much.

**Comment by peterhinch** [comment]
This was fixed by the maintainers.
