### ISSUE TITLE
check_async_code.py

### ISSUE THREAD

**Issue by IhorNehrutsa** [peterhinch/micropython-async#46]
https://github.com/peterhinch/micropython-async/blob/master/check_async_code.py - page not found.

**Comment by peterhinch** [comment]
[Now in V2 directory](https://github.com/peterhinch/micropython-async/blob/master/v2/check_async_code.py) I haven't yet checked that utility against usyncio V3 code.

Where did you find the link, so I can fix it?

**Comment by IhorNehrutsa** [comment]
Thanks. 
But you can't fix it. That is a translation to Russian your tutorial. There is a link to the author under the title. 
https://habr.com/ru/post/484472/
Maybe you might restore an original V2 location?

**Comment by peterhinch** [comment]
Version 2 of uasyncio is essentially obsolete, and I plan to delete the V2 directory and its contents when uasyncio I/O performance is improved. This is promised for the next firmware release 1.14.

Before then I will adapt check_async_code.py for V3 and put it in the V3 directory.

More importantly, the Russian translation appears to be of my V2 tutorial. There are significant differences in uasyncio V3 and I have updated the tutorial [accordingly](https://github.com/peterhinch/micropython-async/blob/master/v3/docs/TUTORIAL.md). I do not know Russian but if you have a means of contacting the author you might want to point this out.

**Comment by IhorNehrutsa** [comment]
I posted the info to the translator.
Thanks again for the job.

**Comment by peterhinch** [comment]
Thank you.
