### ISSUE TITLE
distribute on pypi?

### ISSUE THREAD

**Issue by khusmann** [peterhinch/micropython-async#54]
Thank you for this project!

Have you thought about hosting this as a micropython- package on pypi? It'd be a lot more seamless than having users manually copying primitives. (But perhaps there's a reason for this that I'm missing?)

Thanks again!

**Comment by peterhinch** [comment]
This project is mainly documentation with a collection of code samples. Most of the primitives mimic the CPython primitives and I would expect them to be replaced with official versions when Damien finds time. So I don't think the project is an ideal candidate for PyPi.

**Comment by khusmann** [comment]
> Most of the primitives mimic the CPython primitives and I would expect them to be replaced with official versions when Damien finds time.

Ah, makes sense. Thanks for the reply!
