### ISSUE TITLE
Link/url broken #1

### ISSUE THREAD

**Issue by beyonlo** [peterhinch/micropython-async#65]
Hi Peter!

In the link https://github.com/peterhinch/micropython-async/blob/master/v3/docs/I2C.md has a "This can occur transparently to the application and is covered in detail in section 5.3." where "in section 5.3" is a hyperlink to https://github.com/peterhinch/micropython-async/blob/master/v3/docs/README.md#53-responder-crash-detection where this link do not exists.

Thank you.

**Comment by peterhinch** [comment]
Thanks for the report. At some point I renamed the doc and failed to fix the links, almost all of which were broken. Now fixed.
