### ISSUE TITLE
uasyncio Task Monitor #1

### ISSUE THREAD

**Issue by beyonlo** [peterhinch/micropython-async#66]
Hi Peter.

Great work about the uasyncio Task Monitor (https://github.com/peterhinch/micropython-async/tree/master/v3/as_demos/monitor), congratulations!

The question is: is necessary on the scope one channel for each task that will be monitored?

I have a scope, but it has just two channels.

Thank you.

**Comment by peterhinch** [comment]
No. Just like any circuit with multiple signals, you can move the probes around. Or, alternatively, keep the probes fixed and change the decorators. You might also be interested in the cheap Saleae clones on eBay. I normally disapprove of clones, but Saleae prices are aimed at professionals.
