### ISSUE TITLE
Suggestion: rename CancelError

### ISSUE THREAD

**Issue by antocuni** [peterhinch/micropython-async#7]
This is more a suggestion than an issue, but since I saw that the commits about `NamedCoro` etc. are very recent, I thought it might be a good time to change it before it's too late :).

I think that `CancelError` is very confusing: 
- it's not really an error, it's a part of the flow control: in the same way, we use `StopIteration` instead of `StopIterationError`

- at a first look, it's unclear whether it means that the task was canceled, or whether there was an error while canceling it

Some proposals for a better name:

- `Canceled`
- `NamedCoro.Stop` or `NamedCoro.Canceled`
- `AsyncStop`
- `StopCoroutine`, which is nice because it's similar to `StopIteration`

**Comment by peterhinch** [comment]
Thank you. I agree, I think `StopCoroutine` is perhaps best for the reason you give; although I see Paul is also using the term `task`.

So I wonder if `NamedCoro` should become `NamedTask` and the exception should be `StopTask`? After all `NamedCoro` already has a `task` bound variable.

What do you think?

**Comment by antocuni** [comment]
I like `NamedTask`, especially considering that you start it using `loop.create_task`. 
Then to avoid confusion, the current `NamedCoro.tasks` needs probably to be renamed.

I propose the following:
```python

class NamedTask:
    class Stop(Exception):
        pass
    ...
```

**Comment by cefn** [comment]
Is this equivalent to the CPython name CancelledError ?

https://docs.python.org/3/library/concurrent.futures.html?highlight=cancellederror#concurrent.futures.CancelledError

In CPython, Task#cancel() raises CancelledError within the coroutine itself (at the await) in the same way as calling coro.throw(CancelledError).

https://docs.python.org/3/library/asyncio-task.html?highlight=task%20cancel#asyncio.Task.cancel

**Comment by peterhinch** [comment]
In uasyncio task cancellation works rather differently compared to CPython asyncio. I've attempted to explain this [here](https://github.com/peterhinch/micropython-async/blob/master/TUTORIAL.md#36-task-cancellation). In essence **pend_throw()** is used to throw an exception to the task. This will be handled when the task is next scheduled. This is the mechanism used to implement timeouts.
