### ISSUE TITLE
how urequests become async

### ISSUE THREAD

**Issue by kenjican** [peterhinch/micropython-async#76]
I used to post json by urequests module. Now I need it to be none blocking for efficiency. 

     I  tried uaiohttpclient ,but it seems method get only, no post method. And wrap urequest.post in generator , it doesn't work either. Still blocked.

     If ascyncio could make urequesta to be async?

**Comment by peterhinch** [comment]
I suggest you post this query in [the forum](http://forum.micropython.org/index.php). I have limited experience of web programming.
